<?php



/**
 * Skeleton subclass for performing query and update operations on the 'dkp_activity' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.2-dev on:
 *
 * nie, 13 cze 2010, 14:42:34
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.cre8WowDkpPlugin.lib.model
 */
class DkpActivityQuery extends BaseDkpActivityQuery {

} // DkpActivityQuery
