<?php


/**
 * Skeleton subclass for performing query and update operations on the 'dkp_raid' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.0-dev on:
 *
 * pon, 5 kwi 2010, 17:13:50
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.cre8WowDkpPlugin.lib.model
 */
class DkpRaidQuery extends BaseDkpRaidQuery {

  public function withAll()
  {
    return $this
            ->joinWith('DkpRaid.Dkp')
            ->joinWith('DkpRaid.DkpRaidWowGuildMember', Criteria::LEFT_JOIN)
            ->joinWith('DkpRaidWowGuildMember.DkpRaidActivity', Criteria::LEFT_JOIN)
            ->joinWith('DkpRaidActivity.DkpActivity', Criteria::LEFT_JOIN)
            ->joinWith('DkpRaidWowGuildMember.DkpRaidLoot', Criteria::LEFT_JOIN)
            ->joinWith('DkpRaidLoot.DkpRaidCreature', Criteria::LEFT_JOIN)
            ->useDkpRaidWowGuildMemberQuery()
              ->orderByRank()
            ->endUse()
            ;
  }

} // DkpRaidQuery
